version: '3.8'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs
            - ./vhost:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html

    nginx-proxy-acme:
        image: nginxproxy/acme-companion
        container_name: nginx-proxy-acme
        restart: always
        volumes_from:
            - nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./acme:/etc/acme.sh
        environment:
            - DEFAULT_EMAIL=${ACME_EMAIL}

    redis:
        image: redis:6.2.6-alpine
        container_name: redis
        restart: always
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - '6379:6379'

    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE=${MONGODB_DATABASE_NAME}
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        volumes:
            - ./scripts/db-setup.sh:/docker-entrypoint-initdb.d/db-setup.sh:ro
            - database:/data/db

    frontend:
        image: ghcr.io/utscc09/project-noaccess-frontend
        container_name: frontend
        restart: always
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=hexagon-web.xyz
            - VIRTUAL_PATH=/
            - LETSENCRYPT_HOST=hexagon-web.xyz

    backend:
        image: ghcr.io/utscc09/project-noaccess-backend
        container_name: backend
        depends_on:
            - redis
            - mongodb
        restart: always
        expose:
            - 4000
        environment:
            - MAILGUN_API_KEY=${MAILGUN_API_KEY}
            - VIRTUAL_HOST=hexagon-web.xyz
            - VIRTUAL_PATH=/api
            - LETSENCRYPT_HOST=hexagon-web.xyz
            - NODE_ENV=production
            - MONGODB_URI=${MONGODB_URI}
            - JWT_SECRET=${JWT_SECRET}
            - REDIS_URI=${REDIS_URI}
volumes:
    database:
