name: Build and publish frontend

on:
    push:
        # Only run this workflow if it is a commit to production
        branches:
            - production
        # Only run this workflow if the commit has modified any files the frontend relies on
        paths:
            - frontend/**
            - shared/**

concurrency:
    group: frontend
    cancel-in-progress: true

env:
    IMAGE_NAME: project-noaccess-frontend

jobs:
    # Push image to GitHub Packages.
    push:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'

        steps:
            - uses: actions/checkout@v2

            - name: Build frontend image
              run: docker build -f frontend/Dockerfile --tag $IMAGE_NAME .

            - name: Log into GitHub Container Registry
              run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ secrets.CR_PAT_OWNER }} --password-stdin

            - name: Push image to GitHub Container Registry
              run: |
                  IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
                  # Change all uppercase to lowercase
                  IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
                  # Strip git ref prefix from version
                  VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
                  # Strip "v" prefix from tag name
                  [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
                  # Use Docker `latest` tag convention
                  [ "$VERSION" == "production" ] && VERSION=latest
                  echo IMAGE_ID=$IMAGE_ID
                  echo VERSION=$VERSION
                  docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
                  docker push $IMAGE_ID:$VERSION
